- name: Are we in a docker container ?
  stat:
    path: "/.dockerenv"
  register: docker

- name: Create loopback devices
  shell: "[ ! -e /dev/loop{{ item }} ]] && mknod -m 0666 /dev/loop{{ item }} b 7 {{ item }}"
  loop: "{{ range(0, 20)|list }}"
  failed_when: false
  when: docker.stat.exists
